horizontal
fps
frametime
cpu_stats
gpu_stats
custom_text=GPU/W
gpu_power
position=top-right
font_size=24
background_alpha=0
text_color=FFFFFF
text_outline
text_outline_color=000000
text_outline_thickness=1.5
no_small_font
