fps
fps_color_change=1
fps_value=60,110
fps_color=FF3333,FFAA33,33FF66

frametime
frame_timing=1
frametime_color=33FF66

present_mode

position=top-right
font_size=16
background_alpha=0.25
round_corners=4

toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
toggle_hud_position=Shift_R+F11
