env = __GL_SHADER_DISK_CACHE,1
env = __GL_SHADER_DISK_CACHE_SIZE,10737418240
env = __GL_SHADER_DISK_CACHE_SKIP_CLEANUP,1
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1

cursor {
    no_hardware_cursors = true
}

render {
    direct_scanout = 2
}

# misc { vrr = 2 }  # décommenter quand écran VRR branché

windowrule = immediate on, match:class ^(steam_app_.*)$
windowrule = immediate on, match:class ^(gzw-Win64-Shipping\.exe)$
windowrule = immediate on, match:title ^(Gray Zone Warfare)$

windowrule = opaque on, match:class ^(steam_app_.*)$

windowrule = workspace 4, match:class ^(steam_app_2479810)$
