# précharger les images (optionnel mais recommandé)
preload = /home/axel/Images/wallpapers/l-art-numerique-avec-le-paysage-urbain-et-l-architecture.jpg

# appliquer aux écrans
wallpaper = DP-5,/home/axel/Images/wallpapers/l-art-numerique-avec-le-paysage-urbain-et-l-architecture.jpg
wallpaper = HDMI-A-3,/home/axel/Images/wallpapers/l-art-numerique-avec-le-paysage-urbain-et-l-architecture.jpg

splash = false
